name: Publish Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: https://registry.npmjs.org/
          always-auth: true
          package-manager-cache: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Pack Package
        run: pnpm pack

      - name: Publish to npm (OIDC)
        run: pnpm publish *.tgz --no-git-checks --access public

      - name: Setup Node.js (Github Package)
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          package-manager-cache: false

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm publish *.tgz --no-git-checks

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tgz'
          generate_release_notes: true
